// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvnflirnqgaxbijcbjzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bmZsaXJucWdheGJpamNianppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Mjc5MTcsImV4cCI6MjA2NDMwMzkxN30.aT_VRTFDcivBi0s0HctES__xZBGFCkOV1k2xSvYRtdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);